# Dataset defaults
data:
  base_labels: 'all'
  corpus_labels: 'all'
  train_labels: 'all'
  # For some reason, citeseer's class names are unavailable
  left_out_class_labels: ['Artificial_Intelligence/Machine_Learning/Genetic_Algorithms', 'Artificial_Intelligence/Machine_Learning/Reinforcement_Learning']
  preprocessing: 'none'
  ood_sampling_strategy: all
  train_portion : 20
  test_portion_fixed : 0.2
  split_type: uniform
  type: npz
  drop_train_vertices_portion: 0.1
  precompute_k_hop_neighbourhood: 2
model:
  hidden_sizes: [64]
